version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: sudo apt-get update && sudo apt-get install -y tidy
    - run: git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master) | grep .html | tidy -errors -quiet
